### ISSUE TITLE
Watch media status and broadcast events

### ISSUE THREAD

**Issue by ghenry22** [ghenry22/cordova-chromecast-ios#2]
a GCKMediaControlChannel object is created which has a GCKMediaStatus property.

Need to watch this property for changes and if a change occurs emit a javascript event "playerStatusChanged" with the following values from GCKMediaStatus  included in a javascript object with the emitted event:

mediaSessionID
playerState
idleReason
playbackRate
mediaInformation (sub object including all it's properties)
streamPosition
volume
isMuted

So for example if the player volume is changed, emit an event
if the playerState is changed emit an event
etc

Should potentially ignore updates to the streamPosition to avoid excessive events.

Could potentially also emit some more specific events as well:

Specific events would be:
volumeChanged (on change of volume)
muteChanged (on change of isMuted)
playerStateChanged (on change of playerState, playBackRate)

Need to also implement the getStatus function which can be called from javascript and which returns the same object as above.  There is a stub in place for getStatus already but it doesn't do anything other than log a few things to the native console.

**Comment by orjens** [comment]
Done
Changes of following properties raises playerStatusChanged:
- mediaSessionID
- playerState
- idleReason
- playbackRate
- volume
- isMuted

Implemented additional emitting for: 
- volumeChanged (on change of volume)
- muteChanged (on change of isMuted)
- playerStateChanged (on change of playerState, playBackRate)

**mediaInformation** (sub object including all it's properties) do not changed during playback, no listener needed.

- (void)getChannelStatus:(CDVInvokedUrlCommand*)command;
- (void)getMediaStatus:(CDVInvokedUrlCommand*)command;
for synchronous status requests.

**Comment by ghenry22** [comment]
getChannelStatus works.

getMediaStatus throws an error.  I have captured it from the xcode console and pasted here for reference
![2016-08-01 11_54_01-os x 10 11 - vmware workstation](https://cloud.githubusercontent.com/assets/7463213/17283052/e463f314-57de-11e6-8947-a9a439095e2d.png)

Could you add eventListeners to GCK.js to listen for the status change events and log to console that the event was caught and log the attached json object also to the console.  This will allow me to quickly test that the events are triggering correctly.

**Comment by orjens** [comment]
Changes have been made which should resolve the issue with getMediaStatus

**Comment by ghenry22** [comment]
unfortunately the KVO would only trigger when the entire mediaStatus object was replaced not when the individual values changed.  So it only triggered when loading a new media file.  Unfortunately it also triggered exceptions at that time as loadmedia tries to add KVO each time.

So no events were being broadcast.

I have however, updated the built in callback used by the cast framework for status updates and set this to return mediastatus as dictionary and I can see this event being triggered on change now which is good.

The getmediastatus and getchannel status are both working as is the mediastatus asdictionary.

**Comment by ghenry22** [comment]
this is implemented in dev including passing events with mediaStatus back to javascript plugin.

Need some logic in javascript to emit events for the end user application to receive and act on will open a new ticket for that.
