### ISSUE TITLE
loadMedia success callback

### ISSUE THREAD

**Issue by ghenry22** [ghenry22/cordova-chromecast-ios#3]
Currently loadMedia does not return any result on successful execution.  It should return the playerStatus as discussed in #2 if execution is successful.

**Comment by orjens** [comment]
Done.
Send mediaStatus on load completion from GCKMediaControlChannelDelegate method

**Comment by ghenry22** [comment]
Still no callback received for the loadMedia() method.

**Comment by orjens** [comment]
Change made to andKeepItAlive:YES should fixed the issue.

**Comment by ghenry22** [comment]
I fixed the callback names for loadmedia success and error callbacks in the mediachanneldelegate and set them to return the mediastatusasdictionary and this works now and I can see the events being returned to the javascript component.

I have an odd issue though, the first time loadMedia() is called from a test app it's promise resolves and I get a success callback.

Any subsequent time the promise never resolves so I never get a success callback.  I can see the callback reaching the loadMedia callback in GCK.js and I can log the data returned and it's all correct but for some reason it never resolves the promise to the calling app so it never gets a success callback.

If you could have a look at why this may be that would be great as that is the last thing keeping this issue open.

**Comment by orjens** [comment]
I have changed the Promise logic to resolve it on response from **mediaControlChannelDidUpdateStatus**

**Comment by ghenry22** [comment]
fixed in dev.
